config/routes.rb
Rails.application.routes.draw do
  get 'movies/index'
  # get 'bookmarks/new'
  # get 'bookmarks/create'
  root "lists#index"
  resources :lists, only: [:index, :show, :new, :create, :destroy] do
    resources :bookmarks, only: [:new, :create, :destroy]
  end
  resources :movies, only: [:index]
  # Defines the root path route ("/")
  # root "articles#index"
end

# GET "lists/42/bookmarks/new"
# POST "lists/42/bookmarks"

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie_id, presence: true
  validates :list_id, presence: true
  validates :movie_id, uniqueness: { scope: :list_id }
  validates :comment, length: { minimum: 6,
    too_short: ": %{count} characters is the minimum allowed" }
end

# A bookmark must be linked to a movie and a list, and the [movie, list] pairings should be unique.

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true, uniqueness: true
  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[new create destroy]

  def new
    @bookmark = Bookmark.new
  end

  def search
    @movie = Movie.find(title: params[:query])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show destroy]
  def index
    @lists = List.all
  end

  def show
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to list_path(@list)
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path, status: :see_other
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<div class="container p-5 bg-white">
  <h1>Create a new bookmark</h1>

  <%= simple_form_for [@list, @bookmark], data: { turbo: false } do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie %>
    <%= f.submit "Add bookmark", class: "btn btn-primary"%>
  <% end %>

  <p><%= link_to "Back to menu", lists_path %></p>
</div>

app/views/layouts/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://cdn.pixabay.com/photo/2017/04/29/11/35/movie-2270554_960_720.png);">
  <div class="container">
  <% if @list %>
    <h1 class="animate__animated animate__bounce"><strong><%= @list.name %></strong></h1>
  <% elsif @movies %>
    <h1 class="animate__animated animate__bounce"><strong>All movies</strong></h1>
  <% else %>
    <h1 class="animate__animated animate__bounce"><strong>My lists</strong></h1>
  <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to lists_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "My lists", lists_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
           <%= link_to "New list", new_list_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
           <%= link_to "All movies", movies_path, class: "nav-link" %>
          </li>
          <% if @list && @list.id %>
          <li class="nav-item">
            <%= link_to "Add a bookmark", new_list_bookmark_path(@list.id), class: "nav-link" %>
          </li>
          <% end %>
      </ul>
    <form class="form-inline my-2 my-lg-0">
      <div>
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </div>
    </form>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
  </head>

  <body>
  <%= render "layouts/navbar" %>
    <%= yield %>

  <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.12"></script>

  <script>
  AOS.init();
  </script>
  </body>
</html>

app/views/lists/index.html.erb
<%= render "layouts/banner"%>
<div class="container p-5 bg-white">
    <% @lists.each do |list| %>
  <div class="card-product">
      <img src="https://picsum.photos/200" />
    <div class="card-product-infos">
      <p><%= link_to list.name, list_path(list.id) %></p>
      <%= link_to(list_path(list), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}) do%>
      <i class="fa-solid fa-trash-can"></i>
      <% end %>
    </div>
  </div>
  <% end %>
</div>

app/views/lists/new.html.erb
<div class="container p-5 bg-white">
  <%= simple_form_for(@list) do |f| %>
    <%= f.input :name %>
    <%= f.submit "Add list", class: "btn btn-primary"%>
  <% end %>

  <p><%= link_to "Back to menu", lists_path %></p>
</div>

app/views/lists/show.html.erb
<%= render "layouts/banner"%>
<div class="container p-5 bg-white">
  <div class="cards">
  <% @list.bookmarks.each do |bookmark| %>
    <div class="card-movie" data-aos="flip-down">
    <img src=<%= bookmark.movie.poster_url %>>
    <div class="card-movie-infos">
      <div>
      <h2><%= bookmark.movie.title %> <span style="color: #edc747" class="px-2"><i class="fa-solid fa-star"></i> <%= bookmark.movie.rating %> stars</span>
      <%= link_to(list_bookmark_path(@list, bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}) do%>
        <i class="fa-solid fa-trash-can" style="color:black"></i>
      <% end %></h2>
      <p><%= bookmark.movie.overview %></p>
      <h2><i class="fa-solid fa-quote-left mt-2"></i> <%= bookmark.comment %> <i class="fa-solid fa-quote-right"></i></h2>
      </div>
    </div>
    </div>
  <% end %>
  </div>
</div>

app/views/movies/index.html.erb
<%= render "layouts/banner"%>
<div class="container p-5 bg-white">
  <div class="cards">
  <% @movies.each do |movie| %>
    <div class="card-movie" data-aos="flip-down">
    <img src=<%= movie.poster_url %>>
    <div class="card-movie-infos">
      <div>
      <h2><%= movie.title %> <span style="color: #edc747" class="px-2"><i class="fa-solid fa-star"></i> <%= movie.rating %> stars</span>
      <p><%= movie.overview %></p>
      </div>
    </div>
    </div>
  <% end %>
  </div>
</div>